#!/usr/bin/env python3
"""Validate/render the local runner roadmap, not runtime protocol conformance."""

import argparse
import copy
import json
from pathlib import Path
import re
from urllib.parse import unquote

DOCS = Path(__file__).resolve().parents[1]
ROADMAP = DOCS / "implementation-plan.md"


def require(condition, message):
    if not condition:
        raise ValueError(message)


def validate(plan):
    require(plan["schema_version"] == 1, "unsupported plan version")
    require(plan["status"] == "proposed", "this checker covers a proposed plan")
    require(re.fullmatch(r"[0-9a-f]{40}", plan["source_head"]), "bad source head")
    required = {f"R-{index:02d}" for index in range(1, 25)}
    require(set(plan["requirements"]) == required, "requirement catalog differs")
    require(len(plan["requirements"]) == len(required), "duplicate requirement")
    stages = [stage["id"] for stage in plan["stages"]]
    require(len(stages) == len(set(stages)), "duplicate stage ID")
    order = {stage: index for index, stage in enumerate(stages)}
    tasks = plan["tasks"]
    task_ids = [task["id"] for task in tasks]
    require(len(task_ids) == len(set(task_ids)), "duplicate task ID")
    by_id = {task["id"]: task for task in tasks}
    covered = set()
    for task in tasks:
        require(re.fullmatch(r"MR-\d{2}", task["id"]), "bad task ID")
        require(task["stage"] in stages, "unknown stage")
        for field in ("title", "outcome", "touchpoints", "deliverables",
                      "acceptance", "falsifiers", "requirements"):
            require(bool(task[field]), f"{task['id']}: missing {field}")
        require(set(task["requirements"]) <= required, "unknown requirement")
        require(len(task["depends_on"]) == len(set(task["depends_on"])),
                "duplicate dependency")
        for dependency in task["depends_on"]:
            require(dependency in by_id, "unknown dependency")
            require(order[by_id[dependency]["stage"]] <= order[task["stage"]],
                    "dependency points to later stage")
        covered.update(task["requirements"])
    require(covered == required, f"uncovered requirements: {required - covered}")
    visited, visiting = set(), set()

    def visit(task_id):
        require(task_id not in visiting, "dependency cycle")
        if task_id in visited:
            return
        visiting.add(task_id)
        for dependency in by_id[task_id]["depends_on"]:
            visit(dependency)
        visiting.remove(task_id)
        visited.add(task_id)

    for task_id in task_ids:
        visit(task_id)
    milestone_ids = [item["id"] for item in plan["milestones"]]
    require(len(milestone_ids) == len(set(milestone_ids)), "duplicate milestone")
    for milestone in plan["milestones"]:
        require(bool(milestone["requires"]), "milestone has no gate")
        require(set(milestone["requires"]) <= set(task_ids), "unknown milestone gate")
        require(bool(milestone["claim"]), "milestone has no claim boundary")
    return len(tasks), sum(len(task["depends_on"]) for task in tasks)


def render(plan):
    lines = ["# Mote Run implementation plan", "",
             "<!-- Generated by checks/validate_run_plan.py --write; edit plan.json. -->", "",
             f"{plan['date']}. Status: **{plan['status']}**.", "",
             plan["scope"], "", plan["objective"], "",
             f"First workload: {plan['first_workload']}", "",
             f"Inspected source: `{plan['source_head']}`. Planning issue: `{plan['planning_issue']}`.", "",
             "Read the [audit and workshop](mote-run-audit.md), [architecture](architecture.md),",
             "and [protocol](agent-protocol.md). The [JSON plan](plan.json) owns task IDs,",
             "dependencies and gates. All implementation tasks remain **planned**.", "",
             "## Initial boundary", ""]
    lines += [f"- {item}." for item in plan["exclusions"]]
    lines += ["", "## Milestones", "", "| Milestone | Gate | Permitted claim |", "|---|---|---|"]
    for item in plan["milestones"]:
        lines.append(f"| {item['id']}: {item['title']} | {', '.join(item['requires'])} | {item['claim']} |")
    lines += ["", "## Implementation rules", ""]
    lines += [f"{i}. {rule}" for i, rule in enumerate(plan["execution_rules"], 1)]
    lines += ["", "## Dependency overview", "",
              "Initial path: MR-01 → MR-02 → MR-03 → MR-04 → {MR-05, MR-06} →",
              "MR-07 → MR-08 → MR-09. Analysis branches from MR-07 through MR-11.",
              "Later features have separate gates; none is required for the fake loop.", "",
              "| Task | Stage | Depends on | Outcome |", "|---|---|---|---|"]
    for task in plan["tasks"]:
        lines.append(f"| {task['id']}: {task['title']} | {task['stage']} | "
                     f"{', '.join(task['depends_on']) or 'None'} | {task['outcome']} |")
    for stage in plan["stages"]:
        lines += ["", f"## {stage['id']}: {stage['title']}", "", f"Stage gate: {stage['gate']}"]
        for task in plan["tasks"]:
            if task["stage"] != stage["id"]:
                continue
            lines += ["", f"### {task['id']}: {task['title']}", "", task["outcome"], "",
                      f"Dependencies: {', '.join(task['depends_on']) or 'none'}. "
                      f"Requirements: {', '.join(task['requirements'])}.", "",
                      "Likely touchpoints: " + "; ".join(f"`{p}`" for p in task["touchpoints"]) + "."]
            for field, label in (("deliverables", "Deliverables"), ("acceptance", "Acceptance"),
                                 ("falsifiers", "Failure cases that must be caught"),
                                 ("release_blockers", "Release blockers")):
                if task[field]:
                    lines += ["", f"{label}:", ""]
                    lines += [f"- {value}" for value in task[field]]
    lines += ["", "## Requirement coverage", "",
              "Coverage means a planned owner and gate, not implementation or proof.", "",
              "| Requirement | Planned tasks |", "|---|---|"]
    for requirement in plan["requirements"]:
        owners = [task["id"] for task in plan["tasks"] if requirement in task["requirements"]]
        lines.append(f"| {requirement} | {', '.join(owners)} |")
    lines += ["", "## Reproduce plan checks", "", "```sh",
              "python3 docs/checks/validate_run_plan.py", "```", "",
              "This checks the plan, rendering, local file links and checker negative controls.",
              "It does not validate a runtime schema, execute a harness, or qualify a provider.",
              "See [validation](VALIDATION.md).", ""]
    return "\n".join(lines)


def check_links():
    count = 0
    for document in sorted(DOCS.glob("*.md")):
        for target in re.findall(r"\[[^\]]+\]\(([^)]+)\)", document.read_text()):
            if re.match(r"[a-z]+://", target) or target.startswith("#"):
                continue
            path = unquote(target.split("#", 1)[0])
            require((document.parent / path).exists(), f"missing link: {document.name} -> {target}")
            count += 1
    return count


def negative_controls(plan):
    mutations = [
        lambda p: p["tasks"].append(copy.deepcopy(p["tasks"][0])),
        lambda p: p["tasks"][0]["depends_on"].append(p["tasks"][0]["id"]),
        lambda p: p["tasks"][1]["depends_on"].append("MR-99"),
        lambda p: p["tasks"][0]["requirements"].append("R-99"),
        lambda p: p["tasks"][0].update(acceptance=[]),
        lambda p: p["milestones"][0]["requires"].append("MR-99"),
        lambda p: [task.update(requirements=[r for r in task["requirements"] if r != "R-01"])
                   for task in p["tasks"]],
    ]
    for mutation in mutations:
        variant = copy.deepcopy(plan)
        mutation(variant)
        try:
            validate(variant)
        except ValueError:
            continue
        raise ValueError("negative control was incorrectly accepted")
    return len(mutations)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="regenerate the Markdown roadmap")
    args = parser.parse_args()
    plan = json.loads((DOCS / "plan.json").read_text())
    tasks, edges = validate(plan)
    negatives = negative_controls(plan)
    expected = render(plan)
    if args.write:
        ROADMAP.write_text(expected)
    require(ROADMAP.read_text() == expected, "roadmap differs; rerun with --write")
    links = check_links()
    print(f"PASS: {tasks} tasks, {len(plan['stages'])} stages, {edges} dependency edges, "
          f"24 requirements covered, {negatives} negative controls, "
          f"{links} local file links, generated roadmap exact.")


if __name__ == "__main__":
    main()
